databases:
  - name: reimburse-postgres
    databaseName: reimburse_db
    user: reimburse_user

services:
  - type: web
    name: reimburse-web
    env: python
    buildCommand: "./build.sh"
    startCommand: "gunicorn testproject.wsgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: reimburse-postgres
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
