# Generated by Django 5.2.4 on 2025-07-14 06:48

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True, verbose_name='Nama Role')),
                ('monthly_limit', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Batas Reimbursement Bulanan (Rp)')),
            ],
            options={
                'verbose_name': 'Role Pegawai',
                'verbose_name_plural': 'Role Pegawai',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('personal_number', models.CharField(max_length=20, unique=True, verbose_name='Personal Number')),
                ('full_name', models.CharField(max_length=100, verbose_name='Nama Lengkap')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Email')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Staf')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Tanggal Bergabung')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Pengguna Aplikasi',
                'verbose_name_plural': 'Pengguna Aplikasi',
                'ordering': ['personal_number'],
            },
        ),
        migrations.CreateModel(
            name='ReimbursementRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('submission_date', models.DateTimeField(auto_now_add=True, verbose_name='Tanggal Pengajuan')),
                ('reimburse_date', models.DateField(verbose_name='Tanggal Pengisian BBM')),
                ('fuel_type', models.CharField(choices=[('Pertalite', 'Pertalite'), ('Pertamax', 'Pertamax'), ('Solar', 'Solar'), ('Lainnya', 'Lainnya')], max_length=50, verbose_name='Jenis BBM')),
                ('fuel_amount_liter', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Jumlah Liter BBM')),
                ('fuel_price', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Harga BBM per Liter')),
                ('total_reimbursement_amount', models.DecimalField(decimal_places=2, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Total Biaya Reimbursement (Rp)')),
                ('speedometer_before', models.ImageField(upload_to='reimbursement_proofs/', verbose_name='Speedometer Sebelum')),
                ('speedometer_after', models.ImageField(upload_to='reimbursement_proofs/', verbose_name='Speedometer Sesudah')),
                ('fuel_receipt', models.ImageField(upload_to='reimbursement_proofs/', verbose_name='Struk BBM')),
                ('status', models.CharField(choices=[('Pending', 'Menunggu Persetujuan'), ('Approved', 'Disetujui'), ('Rejected', 'Ditolak'), ('Returned', 'Dikembalikan untuk Revisi'), ('Verified', 'Terverifikasi (Siap Cair)'), ('Paid', 'Sudah Cair')], default='Pending', max_length=20, verbose_name='Status Pengajuan')),
                ('approved_date', models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Disetujui')),
                ('verified_date', models.DateTimeField(blank=True, null=True, verbose_name='Tanggal Diverifikasi')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Catatan')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_requests', to=settings.AUTH_USER_MODEL, verbose_name='Disetujui Oleh')),
                ('owner_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='driver_reimbursements', to=settings.AUTH_USER_MODEL, verbose_name='Pemilik Kendaraan (Jika Driver)')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reimbursement_requests', to=settings.AUTH_USER_MODEL, verbose_name='Pengaju Reimbursement')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_requests', to=settings.AUTH_USER_MODEL, verbose_name='Diverifikasi Oleh')),
            ],
            options={
                'verbose_name': 'Pengajuan Reimbursement',
                'verbose_name_plural': 'Pengajuan Reimbursement',
                'ordering': ['-submission_date'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plat_number', models.CharField(blank=True, max_length=20, null=True, verbose_name='Nomor Plat Kendaraan')),
                ('role', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='core_app.role', verbose_name='Role Pegawai')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL, verbose_name='Akun Pengguna')),
            ],
            options={
                'verbose_name': 'Detail Profil Pengguna',
                'verbose_name_plural': 'Detail Profil Pengguna',
                'ordering': ['user__personal_number'],
            },
        ),
    ]
